import { Pencil } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { formatCurrency } from '@/lib/format';
import type { WizardData } from '../../policy-wizard';

/**
 * Props for the StepReview component.
 */
export interface StepReviewProps {
  data: Partial<WizardData>;
  onEdit: (stepIndex: number) => void;
}

/**
 * Formats line of business for display.
 */
function formatLob(lob?: string): string {
  if (!lob) return '—';
  return lob.replace(/([A-Z])/g, ' $1').trim();
}

/**
 * Review step of the policy wizard.
 */
export function StepReview({ data, onEdit }: StepReviewProps) {
  const { t, i18n } = useTranslation();
  const coverages = data.coverages || [];
  const totalPremium = coverages.reduce((sum, c) => sum + c.premium, 0);

  return (
    <div className="space-y-6">
      {/* Client */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between py-3">
          <CardTitle className="text-base">{t('policies.wizard.steps.client')}</CardTitle>
          <Button variant="ghost" size="sm" onClick={() => onEdit(0)}>
            <Pencil className="mr-1 h-3 w-3" />
            {t('common.actions.edit')}
          </Button>
        </CardHeader>
        <CardContent className="pt-0">
          <p className="text-lg font-medium">{data.clientName || '—'}</p>
        </CardContent>
      </Card>

      {/* Carrier & Product */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between py-3">
          <CardTitle className="text-base">{t('policies.wizard.steps.carrier')}</CardTitle>
          <Button variant="ghost" size="sm" onClick={() => onEdit(1)}>
            <Pencil className="mr-1 h-3 w-3" />
            {t('common.actions.edit')}
          </Button>
        </CardHeader>
        <CardContent className="pt-0">
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <p className="text-sm text-muted-foreground">{t('policies.wizard.review.carrier')}</p>
              <p className="font-medium">{data.carrierName || '—'}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">{t('policies.wizard.review.product')}</p>
              <p className="font-medium">{data.productName || '—'}</p>
              {data.lineOfBusiness && (
                <Badge variant="outline" className="mt-1">
                  {formatLob(data.lineOfBusiness)}
                </Badge>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Policy Details */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between py-3">
          <CardTitle className="text-base">{t('policies.wizard.steps.details')}</CardTitle>
          <Button variant="ghost" size="sm" onClick={() => onEdit(2)}>
            <Pencil className="mr-1 h-3 w-3" />
            {t('common.actions.edit')}
          </Button>
        </CardHeader>
        <CardContent className="pt-0">
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <p className="text-sm text-muted-foreground">{t('policies.wizard.review.policyNumber')}</p>
              <p className="font-medium">{data.policyNumber || t('policies.wizard.review.autoGenerated')}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">{t('policies.wizard.review.effectiveDate')}</p>
              <p className="font-medium">
                {data.effectiveDate
                  ? new Date(data.effectiveDate).toLocaleDateString()
                  : '—'}
              </p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">{t('policies.wizard.review.expirationDate')}</p>
              <p className="font-medium">
                {data.expirationDate
                  ? new Date(data.expirationDate).toLocaleDateString()
                  : '—'}
              </p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">{t('policies.wizard.review.billing')}</p>
              <p className="font-medium">
                {data.billingType === 'DirectBill'
                  ? t('policies.wizard.review.directBill')
                  : t('policies.wizard.review.agencyBill')}{' '}
                / {data.paymentPlan}
              </p>
            </div>
          </div>
          {data.description && (
            <div className="mt-4 border-t pt-4">
              <p className="text-sm text-muted-foreground">{t('policies.wizard.review.notes')}</p>
              <p className="text-sm">{data.description}</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Coverages */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between py-3">
          <CardTitle className="text-base">{t('policies.wizard.steps.coverages')}</CardTitle>
          <Button variant="ghost" size="sm" onClick={() => onEdit(3)}>
            <Pencil className="mr-1 h-3 w-3" />
            {t('common.actions.edit')}
          </Button>
        </CardHeader>
        <CardContent className="pt-0">
          {coverages.length === 0 ? (
            <p className="text-muted-foreground">{t('policies.wizard.review.noCoverages')}</p>
          ) : (
            <div className="space-y-2">
              {coverages.map((coverage) => (
                <div
                  key={coverage.code}
                  className="flex items-center justify-between rounded-lg border p-3"
                >
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-xs text-muted-foreground">
                        {coverage.code}
                      </span>
                      <span className="font-medium">{coverage.name}</span>
                    </div>
                    <div className="mt-1 flex gap-4 text-xs text-muted-foreground">
                      {coverage.limit && (
                        <span>
                          {t('policies.wizard.review.limit')}: ${coverage.limit.toLocaleString()}
                        </span>
                      )}
                      {coverage.deductible && (
                        <span>
                          {t('policies.wizard.review.deductible')}: ${coverage.deductible.toLocaleString()}
                        </span>
                      )}
                    </div>
                  </div>
                  <span className="font-medium">
                    {formatCurrency(coverage.premium, 'USD', i18n.language)}
                  </span>
                </div>
              ))}
              <div className="flex items-center justify-between border-t pt-3">
                <span className="font-medium">{t('policies.wizard.review.totalPremium')}</span>
                <span className="text-xl font-bold">
                  {formatCurrency(totalPremium, 'USD', i18n.language)}
                </span>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
